const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.Rotate.Exps.Speed,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying
	];
};
self.C3_JsPropNameTable = [
	{EllipseBack: 0},
	{EllipseFront: 0},
	{Rotate: 0},
	{Tween: 0},
	{Arrow: 0},
	{Target: 0},
	{TargetHandler: 0},
	{EllipseNumber: 0},
	{Touch: 0},
	{ID: 0},
	{UIText: 0},
	{TargetX: 0},
	{NumberTarget: 0},
	{NumberTargetPanel: 0},
	{ArrayNumber: 0},
	{CurrentTargetFrame: 0},
	{Browser: 0},
	{PlayButton: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{CenterNumber: 0},
	{Loaded: 0},
	{GameState: 0},
	{Score: 0},
	{Highscore: 0},
	{TargetIndex: 0},
	{RotateSpeed: 0},
	{SetRotateSpeed: 0},
	{SFXName: 0}
];

self.InstanceType = {
	EllipseBack: class extends self.ISpriteInstance {},
	EllipseFront: class extends self.ISpriteInstance {},
	Arrow: class extends self.ISpriteInstance {},
	Target: class extends self.ISpriteInstance {},
	TargetHandler: class extends self.ISpriteInstance {},
	EllipseNumber: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	UIText: class extends self.ITextInstance {},
	NumberTarget: class extends self.ISpriteInstance {},
	NumberTargetPanel: class extends self.ISpriteInstance {},
	ArrayNumber: class extends self.IArrayInstance {},
	CurrentTargetFrame: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	PlayButton: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	CenterNumber: class extends self.ISpriteInstance {}
}